[source]
tar = "https://mednafen.github.io/releases/files/mednafen-1.29.0.tar.xz"
patches = [
    "redox.patch",
]

[build]
template = "custom"
dependencies = [
    #TODO: libflac
    "libiconv",
    "liborbital",
    "llvm",
    "mesa",
    "sdl2",
    "zlib",
]
script = """
export SDL_LIBS="-lSDL2 -lorbital $("${TARGET}-pkg-config" --libs osmesa) -lstdc++"
COOKBOOK_CONFIGURE_FLAGS+=(
    --without-libflac
)
cookbook_configure
"""
