[source]
tar = "https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.13.91.tar.xz"
patches = [
	"redox.patch"
]
script = """
wget -O config.sub "https://gitlab.redox-os.org/redox-os/gnu-config/-/raw/master/config.sub?inline=false"
"""

[build]
template = "custom"
dependencies = [
	"expat",
	"freetype",
	"libpng",
	"zlib",
]
script = """
COOKBOOK_CONFIGURE_FLAGS+=(
    --disable-docs \
    ac_cv_func_XML_SetDoctypeDeclHandler=yes
)
cookbook_configure
"""
