[source]
git = "https://github.com/jackpot51/retroarch.git"

[build]
template = "custom"
dependencies = [
    "liborbital",
    "llvm",
    "mesa",
    "openssl",
    "sdl2",
    "zlib",
]
script = """
pushd "${COOKBOOK_SOURCE}"
./fetch-submodules.sh
popd

rsync -av --delete "${COOKBOOK_SOURCE}/" ./

COOKBOOK_CONFIGURE_FLAGS=(
    --host="${TARGET}"
    --prefix="/"
    --disable-builtinzlib # conflicts with zlib
    --disable-discord # does not link
    --disable-netplaydiscovery # missing ifaddrs.h
    --disable-thread_storage # crash in pthread_setspecific called by sthread_tls_set
    --enable-opengl
    --enable-sdl2
    --enable-ssl
    --enable-zlib
)
cookbook_configure
"""
