[source]
tar = "http://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.8.1.tar.xz"
patches = [
    "redox.patch"
]
script = """
wget -O build-aux/config.sub "https://gitlab.redox-os.org/redox-os/gnu-config/-/raw/master/config.sub?inline=false"
"""

[build]
template = "custom"
dependencies = [
    "libiconv"
]
script = """
COOKBOOK_CONFIGURE_FLAGS+=(
    --disable-shared
    --enable-static
    ac_cv_have_decl_program_invocation_name=no
    gt_cv_locale_fr=false
    gt_cv_locale_fr_utf8=false
    gt_cv_locale_ja=false
    gt_cv_locale_tr_utf8=false
    gt_cv_locale_zh_CN=false
)
cookbook_configure
"""
