[source]
git = "https://gitlab.redox-os.org/redox-os/iced.git"
branch = "redox"

[build]
template = "custom"
dependencies = [
    "llvm",
    "mesa",
    "zlib"
]
script = """
    set -x
    ${COOKBOOK_CARGO} rustc \
        --release \
        --manifest-path "${COOKBOOK_SOURCE}/Cargo.toml" \
        --package styling \
        -- \
        -L "${COOKBOOK_SYSROOT}/lib" \
        -C link-args="-Wl,-Bstatic $("${PKG_CONFIG}" --libs osmesa) -lz -lstdc++ -lc -lgcc"
    mkdir -pv "${COOKBOOK_STAGE}/bin"
    cp -v "target/${TARGET}/release/styling" "${COOKBOOK_STAGE}/bin/iced"
"""
