[source]
git = "https://gitlab.redox-os.org/redox-os/iced.git"
branch = "redox"

[build]
template = "custom"
dependencies = [
    "llvm",
    "mesa",
    "zlib"
]
script = """
EXAMPLES=(
    game_of_life
    solar_system
    styling
    tour
)
set -x
for example in "${EXAMPLES[@]}"
do
    ${COOKBOOK_CARGO} rustc \
        --release \
        --manifest-path "${COOKBOOK_SOURCE}/Cargo.toml" \
        --package "${example}" \
        -- \
        -L "${COOKBOOK_SYSROOT}/lib" \
        -C link-args="-Wl,-Bstatic $("${TARGET}-pkg-config" --libs osmesa) -lz -lstdc++ -lc -lgcc"
    mkdir -pv "${COOKBOOK_STAGE}/bin"
    cp -v "target/${TARGET}/release/${example}" "${COOKBOOK_STAGE}/bin/iced_${example}"
done
"""
