[source]
git = "https://gitlab.redox-os.org/redox-os/iced.git"
branch = "redox"

[build]
template = "custom"
dependencies = [
    "llvm",
    "mesa",
    "zlib"
]
script = """
    set -x
    for example in styling tour
    do
        ${COOKBOOK_CARGO} rustc \
            --release \
            --manifest-path "${COOKBOOK_SOURCE}/Cargo.toml" \
            --package "${example}" \
            -- \
            -L "${COOKBOOK_SYSROOT}/lib" \
            -C link-args="-Wl,-Bstatic $("${TARGET}-pkg-config" --libs osmesa) -lz -lstdc++ -lc -lgcc"
        mkdir -pv "${COOKBOOK_STAGE}/bin"
        cp -v "target/${TARGET}/release/${example}" "${COOKBOOK_STAGE}/bin/iced-${example}"
    done
"""
