[source]
tar = "https://github.com/glennrp/libpng/archive/v1.6.36.tar.gz"
script = """
chmod +w config.sub
wget -O config.sub "https://gitlab.redox-os.org/redox-os/gnu-config/-/raw/master/config.sub?inline=false"
"""


[build]
template = "configure"
dependencies = [
    "zlib"
]
